name: CI

on:
  push:
    paths:
      - 'Mifare Classic Tool/**'
  pull_request:
    paths:
      - 'Mifare Classic Tool/**'

env:
  PROJECT_PATH: Mifare Classic Tool

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - name: Build
        working-directory: ${{ env.PROJECT_PATH }}
        run: ./gradlew assemble
      - name: Upload Release Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ env.BUILD_TIME }}
          path: ${{ env.PROJECT_PATH }}/app/build/outputs/apk/debug/*.apk

